version: '3.8'
services:
  orchestrator:
    build: .
    container_name: mildocdms-orchestrator
    ports:
      - "5000:5000"
    environment:
      - MILDOC_SERVICE_URL=http://host.docker.internal:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
